### ISSUE TITLE
[TT 1840] Exception ticking TileEntity c appeng.me.tile.TileStorageBus

### ISSUE THREAD

**Issue by solomon56** [MinimallyCorrect/TickThreading#684] opened 2013-06-09 07:48 UTC
2013-06-09 00:46:52 [INFO] [TickThreading] Threading initialised for world Nexus/8
2013-06-09 00:46:53 [SEVERE] [TickThreading] Exception ticking TileEntity c appeng.me.tile.TileStorageBus @2125499273 in Overworld/0 at x, y, z: -340, 73, 137
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:819)
        at java.util.ArrayList$Itr.next(ArrayList.java:791)
        at appeng.me.tile.TileStorageBus.g(TileStorageBus.java:129)
        at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:93)
        at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
        at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-09 00:46:53 [SEVERE] [TickThreading] Exception ticking TileEntity c appeng.me.tile.TileStorageBus @1800605837 in Overworld/0 at x, y, z: -340, 73, 139
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:819)
        at java.util.ArrayList$Itr.next(ArrayList.java:791)
        at appeng.me.tile.TileStorageBus.g(TileStorageBus.java:129)
        at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:93)
        at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
        at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-06-09 00:46:53 [SEVERE] [TickThreading] Exception ticking TileEntity c appeng.me.tile.TileStorageBus @1192344258 in Overworld/0 at x, y, z: -340, 73, 140
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:819)
        at java.util.ArrayList$Itr.next(ArrayList.java:791)
        at appeng.me.tile.TileStorageBus.g(TileStorageBus.java:129)
        at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:93)
        at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
        at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:102)
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
        at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by alicheek** [comment] 2013-06-09 17:26
Duplicate of #649

**Closed as completed** 2013-06-09 19:55 UTC
Labels: duplicate
