### ISSUE TITLE
[MCPC 67] [TT1932] [SEVERE] [TickThreading] Failed to handle packet from unknown

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#791] opened 2013-06-20 16:42 UTC
2013-06-20 16:59:54 [SEVERE] [TickThreading] Failed to handle packet from unknown
java.io.IOException: Received string length longer than maximum allowed (8704 > 16)
    at ef.a(Packet.java:240)
    at cy.a(Packet2ClientProtocol.java:33)
    at ef.a(Packet.java:175)
    at cg.i(TcpConnection.java:325)
    at cg.readNetworkPacket(TcpConnection.java:71)
    at ch.run(ReplaceTcpReaderThread.java:22)

**Comment by alicheek** [comment] 2013-06-20 16:43
[SEVERE] [TickThreading] Failed to handle packet from unknown
java.io.IOException: Received string length longer than maximum allowed (7936 > 16)
    at ef.a(Packet.java:240)
    at cy.a(Packet2ClientProtocol.java:33)
    at ef.a(Packet.java:175)
    at cg.i(TcpConnection.java:325)
    at cg.readNetworkPacket(TcpConnection.java:71)
    at ch.run(ReplaceTcpReaderThread.java:22)

**Comment by LunNova** [comment] 2013-06-20 16:53
Duplicate of #674.

**Closed as completed by LunNova** 2013-06-20 16:53 UTC
Labels: duplicate
