### ISSUE TITLE
Itemducts disconnect, items spill on the ground.

### ISSUE THREAD

**Issue by ProsperCraft** [MinimallyCorrect/TickThreading#1199] opened 2014-05-28 13:29 UTC
FTB Agrarian Skies 2.1.6
TickThreading-1.6.4.230
MCPC Plus

Itemducts are randomly disconnecting, I have seen items spilling onto the ground.

**Comment by ghost** [comment] 2014-05-28 14:50
Some more info on this bug for you. The world was already created and running and TickThresding was added after the fact. I have noticed that most of the problems seem to be as duct cross chunk lines.

**Comment by BlackAce21** [comment] 2014-05-28 17:31
I am with those 2 ^

Additionally, console is spitting out null pointer errors for the TE pulverizer in the console, its also accepting items from input devices like hoppers that it shouldn't and has no recipe for then tries to process them.

With the itemducts the issue is happening repeatedly and happens on chunk unload. I have seen reports that a chunk loader will curb it from happening but have yet to test this myself. I know that AS is behind by several versions in Forge Multiparts because we are also having client side disconnects with key not found exceptions. Research I was able to dig up says thats fixed in an updated version, however we weren't having those crashes before we added Tick Threading. Whether its the outdated multipart version, or bad interaction with Tick Threading, its hard to say.

**Closed as completed** 2016-01-09 22:43 UTC
Labels: bug
