### ISSUE TITLE
[TT-1.6.4.223] [MCPC] [1.6.4] [SEVERE] [TickThreading] Exception in main tick loop

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#1175] opened 2014-05-26 14:22 UTC
[SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
    at thermalexpansion.part.conduit.fluid.GridFluid.doGridUpdate(GridFluid.java:63)
    at thermalexpansion.part.conduit.GridTickHandler.tickEnd(GridTickHandler.java:75)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
    at nallar.tickthreading.util.WrappedScheduledTickHandler.tickEnd(WrappedScheduledTickHandler.java:27)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:80)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick_cpw_mods_fml_common_FMLCommonHandler_onPreServerTick_p0(FMLCommonHandler.java:274)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:330)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:183)
    at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)

spamming the ttlog already got 56mb worth of it when its been up for 20 mins :P

**Comment by LunNova** [comment] 2014-05-26 14:26
Duplicate of #1122.

**Closed as completed by LunNova** 2014-05-26 14:26 UTC
Labels: duplicate
