### ISSUE TITLE
Me autocraft starting to lag the server ?

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#437] opened 2013-05-03 18:37 UTC
was in build 1502/1503,and i noticed dis started to happen, i never seen ME in the /profile e list till today

![2013-05-03_21 26 19](https://f.cloud.github.com/assets/3189195/460458/976a3642-b41f-11e2-940c-8e3ff527cef9.png)

also there is huge lag spike when ME system receives a craft command (multiple tests )

![2013-05-03_21 25 57](https://f.cloud.github.com/assets/3189195/460491/6ddaf158-b420-11e2-84ec-0d861fe46671.png)

![2013-05-03_18 49 45](https://f.cloud.github.com/assets/3189195/460466/fa83b0b4-b41f-11e2-8ffc-281f19657cbf.png)

build i had before that was ok was 1493, no lag from ME,

**Comment by LunNova** [comment] 2013-05-03 18:54
That's a few too many significant figures of TPS, oops!

AE has performance issues in the version in use in FTB ultimate, it needs updated. Not really much I can do.

**Comment by LunNova** [comment] 2013-05-03 18:55
Get a jvisualvm CPU sampler snapshot and I can check that it's definitely not caused by a TT change, and possibly fix the issue.

**Comment by HaoSs07** [comment] 2013-05-03 19:04
not sure i can do that, the server is hosted along multiple cs,samp and minecraft servers.
and i dont have full access to root

**Comment by cjm721** [comment] 2013-05-03 19:25
I had this issue for a while since even before I installed TT on my ultimate pack server.

I am using an AutoCrafter that is 13x13x6 and if I do any multi level crafting it causes lag to a point I can crash the server.

I also believe this has been fixed rv10.a when he was doing alot of his network performance upgrades.

**Comment by HaoSs07** [comment] 2013-05-03 19:27
good to know. hope ftb will update soon to 1.5
is strange that till today i had no problem with ME lag, and i have the same system i had a month ago(when my motherboard crashed and i did not play. just maintain the server)

**Comment by cjm721** [comment] 2013-05-03 19:32
Sure it is the same? One export line on craft code is what caused my original crash with it. Running 1502 also and have not had any issues yet. I did notice on the profile that the tile controller appears twice at the same location, you could try breaking and replacing it as that has fixed a locked system for me before.

**Comment by LunNova** [comment] 2013-05-03 21:46
You don't need root access, you just need to be able to change your java arguments.

**Comment by HaoSs07** [comment] 2013-05-03 22:11
well why no provide them in the first place ?

**Comment by LunNova** [comment] 2013-05-03 22:14
https://visualvm.java.net/jmx_connections.html

**Comment by HaoSs07** [comment] 2013-05-03 22:53
the server is fu**ing with me, im connected to the jmx. but now... there is no lag.
same system. When i made this problem i had lag when requested a fusion coil,tested multiple times with 02 and 03 builds
Now i requested 20. and it started crafting whit no delay 
![2013-05-04_01 49 19](https://f.cloud.github.com/assets/3189195/461650/01a3aefc-b444-11e2-94d9-8488a62e2deb.png)

heres the snapshot anyway
https://dl.dropboxusercontent.com/u/76651664/ftbHaoSs1.nps

**Comment by HaoSs07** [comment] 2013-05-03 23:24
well managed to find a problem, if not "the" problem .  fore some reason when storage bus is connected to a black hole chest the system lags, probably not TT related. 
snapshot anyway.

 https://dl.dropboxusercontent.com/u/76651664/ftbHaoSs2.nps

thx for time

**Comment by Puremin0rez** [comment] 2013-05-04 00:41
I ended up pulling the mod, I was getting the same type of issues... not worth the heavy lag.

**Comment by LunNova** [comment] 2013-05-04 12:54
Closing this, as there's not much I can do short of redesigning the way AE uses inventories. That's already been done, just the ultimate pack is out of date.

**Closed as completed by LunNova** 2013-05-04 12:54 UTC
Labels: performance
