### ISSUE TITLE
Build 1356 Xycraft tanks not saving on shutdown

### ISSUE THREAD

**Issue by Kusinagie** [MinimallyCorrect/TickThreading#346] opened 2013-04-19 23:09 UTC
Started using Xycraft tanks and i noticed on a restart of the server the tank is not formed any longer and the contents lost. Happens every restart. No errors in log that i can see.

**Comment by LunNova** [comment] 2013-04-19 23:10
Duplicate of #305.

**Closed as completed by LunNova** 2013-04-19 23:10 UTC
Labels: duplicate
