### ISSUE TITLE
[SEVERE] [TickThreading] world/-1 has become unstable, stopping.

### ISSUE THREAD

**Issue by Lakart** [MinimallyCorrect/TickThreading#898] opened 2013-07-14 18:49 UTC
Continually happens across worlds and installs. Already had to kill half a dozen worlds due to this, and the one it just happened one was a brand new fresh install.

Server Log: http://pastebin.com/epLhtBUV
Patcher Log: http://pastebin.com/r9GR76gq
TT Log: http://pastebin.com/vsZ0LbYc

**Comment by LunNova** [comment] 2013-07-14 21:12
In general, "a world has become unstable" doesn't mean the world is broken - just that some issue happened ticking that world. Like in this case, it may be an issue which can happen randomly and to any world.

Duplicate of #784, will fix that soon.

**Closed as completed by LunNova** 2013-07-14 21:12 UTC
Labels: duplicate

**Comment by LunNova** [comment] 2013-07-14 21:22
Fixed in latest.
