### ISSUE TITLE
Build #1383 - [WARNING] [TickThreading]

### ISSUE THREAD

**Issue by DrFestus** [MinimallyCorrect/TickThreading#358] opened 2013-04-20 15:36 UTC
Getting spammed in my console with:

[WARNING] [TickThreading] World worldname/0's dimensionId was set incorrectly, changing from 0 to whatevernumber

Also got alot of this after the server starts with build 1383

[SEVERE] java.util.ConcurrentModificationException
2013-04-20 11:27:51 [SEVERE]    at java.util.ArrayList.writeObject(Unknown Source)
2013-04-20 11:27:51 [SEVERE]    at sun.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
2013-04-20 11:27:51 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2013-04-20 11:27:51 [SEVERE]    at java.lang.reflect.Method.invoke(Unknown Source)
2013-04-20 11:27:51 [SEVERE]    at java.io.ObjectStreamClass.invokeWriteObject(Unknown Source)
2013-04-20 11:27:51 [SEVERE]    at java.io.ObjectOutputStream.writeSerialData(Unknown Source)
2013-04-20 11:27:51 [SEVERE]    at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
2013-04-20 11:27:51 [SEVERE]    at java.io.ObjectOutputStream.writeObject0(Unknown Source)
2013-04-20 11:27:51 [SEVERE]    at java.io.ObjectOutputStream.writeObject(Unknown Source)
2013-04-20 11:27:51 [SEVERE]    at twilightforest.TFFeatureCache.save(TFFeatureCache.java:120)
2013-04-20 11:27:51 [SEVERE]    at twilightforest.world.TFWorldChunkManager.saveFeatureCache(TFWorldChunkManager.java:415)
2013-04-20 11:27:51 [SEVERE]    at twilightforest.TFEventListener.worldSave(TFEventListener.java:429)
2013-04-20 11:27:51 [SEVERE]    at net.minecraftforge.event.ASMEventHandler_132_TFEventListener_worldSave_Save.invoke(.dynamic)
2013-04-20 11:27:51 [SEVERE]    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
2013-04-20 11:27:51 [SEVERE]    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
2013-04-20 11:27:51 [SEVERE]    at in.a(WorldServer.java:150)
2013-04-20 11:27:51 [SEVERE]    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:461)
2013-04-20 11:27:51 [SEVERE]    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:555)
2013-04-20 11:27:51 [SEVERE]    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
2013-04-20 11:27:51 [SEVERE]    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
2013-04-20 11:27:54 [SEVERE] java.util.ConcurrentModificationException
2013-04-20 11:27:54 [SEVERE]    at java.util.ArrayList.writeObject(Unknown Source)
2013-04-20 11:27:54 [SEVERE]    at sun.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
2013-04-20 11:27:54 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2013-04-20 11:27:54 [SEVERE]    at java.lang.reflect.Method.invoke(Unknown Source)
2013-04-20 11:27:54 [SEVERE]    at java.io.ObjectStreamClass.invokeWriteObject(Unknown Source)
2013-04-20 11:27:54 [SEVERE]    at java.io.ObjectOutputStream.writeSerialData(Unknown Source)
2013-04-20 11:27:54 [SEVERE]    at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
2013-04-20 11:27:54 [SEVERE]    at java.io.ObjectOutputStream.writeObject0(Unknown Source)
2013-04-20 11:27:54 [SEVERE]    at java.io.ObjectOutputStream.writeObject(Unknown Source)
2013-04-20 11:27:54 [SEVERE]    at twilightforest.TFFeatureCache.save(TFFeatureCache.java:120)
2013-04-20 11:27:54 [SEVERE]    at twilightforest.world.TFWorldChunkManager.saveFeatureCache(TFWorldChunkManager.java:415)
2013-04-20 11:27:54 [SEVERE]    at twilightforest.TFEventListener.worldSave(TFEventListener.java:429)
2013-04-20 11:27:54 [SEVERE]    at net.minecraftforge.event.ASMEventHandler_132_TFEventListener_worldSave_Save.invoke(.dynamic)
2013-04-20 11:27:54 [SEVERE]    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
2013-04-20 11:27:54 [SEVERE]    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
2013-04-20 11:27:54 [SEVERE]    at in.a(WorldServer.java:150)
2013-04-20 11:27:54 [SEVERE]    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:461)
2013-04-20 11:27:54 [SEVERE]    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:555)
2013-04-20 11:27:54 [SEVERE]    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
2013-04-20 11:27:54 [SEVERE]    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
2013-04-20 11:27:55 [SEVERE] java.util.ConcurrentModificationException
2013-04-20 11:27:55 [SEVERE]    at java.util.ArrayList.writeObject(Unknown Source)
2013-04-20 11:27:55 [SEVERE]    at sun.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)
2013-04-20 11:27:55 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2013-04-20 11:27:55 [SEVERE]    at java.lang.reflect.Method.invoke(Unknown Source)
2013-04-20 11:27:55 [SEVERE]    at java.io.ObjectStreamClass.invokeWriteObject(Unknown Source)
2013-04-20 11:27:55 [SEVERE]    at java.io.ObjectOutputStream.writeSerialData(Unknown Source)
2013-04-20 11:27:55 [SEVERE]    at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
2013-04-20 11:27:55 [SEVERE]    at java.io.ObjectOutputStream.writeObject0(Unknown Source)
2013-04-20 11:27:55 [SEVERE]    at java.io.ObjectOutputStream.writeObject(Unknown Source)
2013-04-20 11:27:55 [SEVERE]    at twilightforest.TFFeatureCache.save(TFFeatureCache.java:120)
2013-04-20 11:27:55 [SEVERE]    at twilightforest.world.TFWorldChunkManager.saveFeatureCache(TFWorldChunkManager.java:415)
2013-04-20 11:27:55 [SEVERE]    at twilightforest.TFEventListener.worldSave(TFEventListener.java:429)

**Comment by LunNova** [comment] 2013-04-20 17:34
Closing as duplicate of #341.

**Closed as completed by LunNova** 2013-04-20 17:34 UTC
Labels: duplicate
