### ISSUE TITLE
disconnect.overflow

### ISSUE THREAD

**Issue by darkdeath1332** [MinimallyCorrect/TickThreading#695] opened 2013-06-10 18:48 UTC
My server had yesterday 80 poeple online without any problems, since today alot of players get disconnected with: 'disconnect.overflow'. Now most of my players can even play.

This is my network status:
![image](https://f.cloud.github.com/assets/3824354/633415/45670a30-d1fe-11e2-8cb3-437d3f870327.png)

**Comment by darkdeath1332** [comment] 2013-06-10 18:52
ZollieXavier lost connection: disconnect.overflow

**Comment by LunNova** [comment] 2013-06-10 20:52
Use aPerf to find the problem, looks like a mod has broken and is spamming packets.

**Comment by LunNova** [comment] 2013-06-10 21:33
Going to add profiling for this to TT, as aPerf can't be used with MCPC+.

**Comment by darkdeath1332** [comment] 2013-06-10 21:39
Awesome, also try to fix the TP bugs. The TP bugs are not happening when I dont have TT installed.

**Comment by LunNova** [comment] 2013-06-11 00:31
Partially implemented the profiling in latest, using `/profile p`. Haven't had time to make it split up 250CustomPayload packets, so all mod packets will be grouped together as 250CustomPayload.

This probably means that it is not yet useful for finding which mod is causing your problem, will have that done tomorrow.

**Comment by LunNova** [comment] 2013-06-11 23:16
This change will prevent some types of packet spam, due to block and/or tile entity updates.

**Comment by LunNova** [comment] 2013-06-11 23:32
Update to latest, run `/profile p`. It should show which mod is spamming packets now.

**Comment by darkdeath1332** [comment] 2013-06-12 15:33
It was an issue with the host its network.

**Comment by LunNova** [comment] 2013-06-12 15:38
Please still get that profiling information, bandwidth usage is much higher than it should be, and it may cause issues for users on slow connections.

**Comment by alicheek** [comment] 2013-06-12 15:40
yea must admit ive got a slow connection and some times I have issues with this where I just keep getting dced lol but as u said its because I have terrible internet about 250kB down and 60kB up

**Comment by LunNova** [comment] 2013-06-12 17:47
Screenshot isn't helpful, follow the instructions in the second link I gave earlier to export it.

**Comment by darkdeath1332** [comment] 2013-06-12 18:00
```
                                 Packet |  Count |     Size
                          mmmPowerSuits | 440202 | 39463926
```

**Comment by darkdeath1332** [comment] 2013-06-12 18:00
That could be my issue

**Comment by darkdeath1332** [comment] 2013-06-12 18:16
```
                                 Packet |  Count |      Size
                          mmmPowerSuits | 475447 |  42263529
                                     CC |  51365 | 115618771
                                    ic2 |  31393 |   1009620
```

**Comment by LunNova** [comment] 2013-06-16 15:42
Caused by packet spam, MPS packet spam fixed via 8e0e63a7b5cbf3e14f0525f906b7d27d08c023dd.

**Closed as completed by LunNova** 2013-06-16 15:42 UTC
Labels: bug

**Comment by darkdeath1332** [comment] 2013-06-16 18:57
How did you fix it? I have unbanned the items again and its still eating my network on latest TT.

Also is It bad that CC uses so many network?

![image](https://f.cloud.github.com/assets/3824354/659710/9e8ce532-d6b6-11e2-8a78-d403a7607d88.png)

**Comment by LunNova** [comment] 2013-06-16 18:59
It's still very bad, but it's nowhere near as bad as it used to be.

It's terrible that CC's doing that, probably a good idea to ask on CC forums about this.

**Comment by darkdeath1332** [comment] 2013-06-16 19:21
Thank you very much for your great work, If you didnt make TT no server could be this big.
