### ISSUE TITLE
 Unhandled exception in worker thread Entities in Overworld/0 - 4

### ISSUE THREAD

**Issue by ThuGie** [MinimallyCorrect/TickThreading#686] opened 2013-06-09 19:54 UTC
[SEVERE] [TickThreading] Unhandled exception in worker thread Entities in Overworld/0 - 4
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
        at java.util.ArrayList$Itr.next(Unknown Source)
        at me.nallar.tickthreading.minecraft.TickManager.fixDiscrepancies(TickManager.java:589)
        at me.nallar.tickthreading.minecraft.TickManager$1.run(TickManager.java:549)
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
        at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by LunNova** [comment] 2013-06-09 19:55
Duplicate of #676

**Closed as completed by LunNova** 2013-06-09 19:55 UTC
Labels: duplicate
