### ISSUE TITLE
Console Spam with Blood and Bones 1.07 and TT 229

### ISSUE THREAD

**Issue by Yabdat** [MinimallyCorrect/TickThreading#1177] opened 2014-05-26 15:52 UTC
Tried out TT  build 229 with the Blood and Bones 1.07. No crashes, but getting serious console spam.
This message gets spammed in console about every 20 seconds, seems to not cause any crashes as far as I can see, but still annoying.

Zombie Awareness doesn't seem to like TT much.. :)

05-26 17:46:30 [INFO] [STDOUT] SERIOUS REFLECTION FAIL IN DimensionChunkCache
05-26 17:46:30 [INFO] [STDERR] java.lang.NullPointerException
05-26 17:46:30 [INFO] [STDERR]  at CoroAI.DimensionChunkCache.<init>(DimensionChunkCache.java:83)
05-26 17:46:30 [INFO] [STDERR]  at CoroAI.DimensionChunkCache.updateAllWorldCache(DimensionChunkCache.java:53)
05-26 17:46:30 [INFO] [STDERR]  at CoroAI.PFQueue.tryPath(PFQueue.java:556)
05-26 17:46:30 [INFO] [STDERR]  at CoroAI.PFQueue.tryPath(PFQueue.java:538)
05-26 17:46:30 [INFO] [STDERR]  at CoroAI.PFQueue.getPath(PFQueue.java:511)
05-26 17:46:30 [INFO] [STDERR]  at ZombieAwareness.ZAUtil.ai_FindSense(ZAUtil.java:370)
05-26 17:46:30 [INFO] [STDERR]  at ZombieAwareness.ZAUtil.aiTick(ZAUtil.java:254)
05-26 17:46:30 [INFO] [STDERR]  at ZombieAwareness.ZombieAwareness.worldTick(ZombieAwareness.java:265)
05-26 17:46:30 [INFO] [STDERR]  at ZombieAwareness.ZombieAwareness.onTickInGame(ZombieAwareness.java:223)
05-26 17:46:30 [INFO] [STDERR]  at ZombieAwareness.ZombieAwareness.onTick(ZombieAwareness.java:195)
05-26 17:46:30 [INFO] [STDERR]  at ZombieAwareness.ServerTickHandler.onTickInGame(ServerTickHandler.java:54)
05-26 17:46:30 [INFO] [STDERR]  at ZombieAwareness.ServerTickHandler.tickEnd(ServerTickHandler.java:33)
05-26 17:46:30 [INFO] [STDERR]  at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
05-26 17:46:30 [INFO] [STDERR]  at nallar.tickthreading.util.WrappedScheduledTickHandler.tickEnd(WrappedScheduledTickHandler.java:27)
05-26 17:46:30 [INFO] [STDERR]  at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:80)
05-26 17:46:30 [INFO] [STDERR]  at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick_cpw_mods_fml_common_FMLCommonHandler_onPreServerTick_p0(FMLCommonHandler.java:274)
05-26 17:46:30 [INFO] [STDERR]  at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java)
05-26 17:46:30 [INFO] [STDERR]  at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:330)
05-26 17:46:30 [INFO] [STDERR]  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:183)
05-26 17:46:30 [INFO] [STDERR]  at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
05-26 17:46:30 [INFO] [STDOUT] DimensionChunkCache crash, tell Corosus

**Comment by LunNova** [comment] 2014-05-26 16:04
Duplicate of #1084. Fixed.

**Closed as completed by LunNova** 2014-05-26 16:04 UTC
Labels: duplicate
