### ISSUE TITLE
Crashing when teleporting

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#1143] opened 2014-05-19 19:06 UTC
Before tickthreading I never had this crash issue before but after installing it when I teleport I get this very often now:

Description: Exception in world tick

java.util.NoSuchElementException: key not found: codechicken.lib.vec.BlockCoord@fffb1a3e
    at scala.collection.MapLike$class.default(MapLike.scala:228)
    at scala.collection.AbstractMap.default(Map.scala:58)
    at scala.collection.mutable.HashMap.apply(HashMap.scala:64)
    at codechicken.multipart.TileMultipart$$anonfun$tilemp$lzycompute$1$1.apply(TileMultipart.scala:647)
    at codechicken.multipart.TileMultipart$$anonfun$tilemp$lzycompute$1$1.apply(TileMultipart.scala:647)
    at scala.Option.getOrElse(Option.scala:120)
    at codechicken.multipart.TileMultipart$.tilemp$lzycompute$1(TileMultipart.scala:647)
    at codechicken.multipart.TileMultipart$.tilemp$1(TileMultipart.scala:647)
    at codechicken.multipart.TileMultipart$.handlePacket(TileMultipart.scala:656)
    at codechicken.multipart.handler.MultipartCPH$.handleCompressedTileData(packethandlers.scala:72)
    at codechicken.multipart.handler.MultipartCPH$.handlePacket(packethandlers.scala:44)
    at codechicken.lib.packet.PacketCustom$ClientTinyPacketHandler.handle(PacketCustom.java:216)
    at codechicken.lib.packet.PacketCustom$CustomTinyPacketHandler.handle(PacketCustom.java:235)
    at cpw.mods.fml.common.network.NetworkRegistry.handleTinyPacket(NetworkRegistry.java:354)
    at cpw.mods.fml.common.network.FMLNetworkHandler.handlePacket131Packet(FMLNetworkHandler.java:430)
    at net.minecraft.client.multiplayer.NetClientHandler.func_72494_a(NetClientHandler.java:1514)
    at net.minecraft.network.packet.Packet131MapData.func_73279_a(SourceFile:41)
    at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:462)
    at net.minecraft.client.multiplayer.NetClientHandler.func_72551_d(NetClientHandler.java:281)
    at net.minecraft.client.multiplayer.WorldClient.func_72835_b(WorldClient.java:99)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1930)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:910)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

**Comment by LunNova** [comment] 2014-05-21 22:37
Duplicate of #1083.

**Closed as completed by LunNova** 2014-05-21 22:37 UTC
Labels: duplicate
