### ISSUE TITLE
[TT 1684, MCPC+ L33]Exception ticking world Age 118/118 yh: The save is being accessed from another location, aborting

### ISSUE THREAD

**Issue by wormzjl** [MinimallyCorrect/TickThreading#559] opened 2013-05-25 09:09 UTC
Getting this console spam with latest TT and MCPC, I have absolutely nothing else accessing these savedata

2013-05-24 12:46:49 [SEVERE] [TickThreading] Exception ticking world Age 118/118
yh: The save is being accessed from another location, aborting
    at ahv.c(SaveHandler.java:113)
    at yc.D(World.java:4598)
    at in.a(WorldServer.java:1104)
    at in.a(WorldServer.java:158)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:521)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:623)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by wormzjl** [comment] 2013-05-26 11:49
Also getting some of these:
2013-05-25 23:25:44 [SEVERE] [TickThreading] Chunk save may have failed for -124554051662: -78,-30
2013-05-25 23:25:44 [SEVERE] [TickThreading] While unloading chunk at -78,-30 which is unloaded and populated it was replaced/removed from the unloadingChunks map.

**Comment by LunNova** [comment] 2013-05-27 10:03
Did the first error occur after a world unloaded?

**Comment by LunNova** [comment] 2013-05-27 10:09
Also, are you using a backup plugin or mod? iirc there was one which sometimes caused this.

**Comment by wormzjl** [comment] 2013-05-27 10:59
No I'm not using any backup plugin.
The first message disappeared with the latest build, but I got this one instead:
2013-05-27 01:38:09 [SEVERE] [TickThreading] Failed to save chunk in Overworld/0 -58, -51

**Comment by LunNova** [comment] 2013-05-27 11:21
That's very not good. Can you please update to latest?

Either the issue will be fixed, if it's the one fixed in 1ce359a536549f4008, or it will still be there and also actually log a stack trace.

**Comment by wormzjl** [comment] 2013-05-27 15:50
No such errors after the update, but I got a lot of these now, dunno if it's related:
https://github.com/nallar/TickThreading/issues/572

**Comment by LunNova** [comment] 2013-05-31 10:40
This was probably caused by duplicate loading of a world, which should now be fixed. Still happening?

**Comment by wormzjl** [comment] 2013-05-31 22:23
No IMO it's fixed now.

**Closed as completed** 2013-05-31 22:23 UTC
Labels: bug
