### ISSUE TITLE
[TT 1859, MCPC L67] [SEVERE] [ForgeModLoader] Encountered an unexpected exceptionNoClassDefFoundError

### ISSUE THREAD

**Issue by mainsheep** [MinimallyCorrect/TickThreading#700] opened 2013-06-11 09:16 UTC
Server randomly crashes.

> 2013-06-11 04:13:56 [SEVERE] [ForgeModLoader] Encountered an unexpected exceptionNoClassDefFoundError
> java.lang.NoClassDefFoundError: Could not initialize class miscperipherals.util.Util
>         at miscperipherals.asm.ASMHelper.getTurtleBlockLightValue(ASMHelper.java:32)
>         at dan200.turtle.shared.BlockTurtle.getLightValue(BlockTurtle.java)
>         at yc.g(World.java:3889)
>         at yc.c(World.java:3956)
>         at yc.z(World.java:3828)
>         at yc.a(World.java:770)
>         at yc.c(World.java:746)
>         at yc.d(World.java:987)
>         at vq.placeBlockAt(ItemBlock.java:264)
>         at yc.a(World.java:4367)
>         at vq.a(ItemBlock.java:98)
>         at dan200.computer.shared.ItemComputerBase.a(ItemComputerBase.java:50)
>         at ur.a(ItemStack.java:135)
>         at ir.a(ItemInWorldManager.java:580)
>         at iv.a(NetServerHandler.java:906)
>         at fk.a(Packet15Place.java:79)
>         at cg.b(TcpConnection.java:467)
>         at iv.d(NetServerHandler.java:220)
>         at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:57)
>         at iw.b(NetworkListenThread.java)
>         at ht.b(DedicatedServerListenThread.java:34)
>         at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:417)
>         at ho.r(DedicatedServer.java:309)
>         at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:292)
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:194)
>         at fy.run(ThreadMinecraftServer.java:16)
> 04:13:56 [SEVERE] This crash report has been saved to: /minecraft/Minecraft/./crash-reports/crash-2013-06-11_04.13.56-server.txt

**Comment by mainsheep** [comment] 2013-06-11 09:52
It seems like it's a problem with turtles. It's crashing the server instantly. Earlier build TT1851 also has this problem.

**Comment by LunNova** [comment] 2013-06-15 19:18
Caused by the same problem which caused #702, which is now fixed.

**Closed as completed by LunNova** 2013-06-15 19:18 UTC
Labels: bug
