### ISSUE TITLE
[TT #1543, MCPC+ L22] Client crash with forestry machines after updating TT

### ISSUE THREAD

**Issue by wormzjl** [MinimallyCorrect/TickThreading#452] opened 2013-05-06 09:08 UTC
After update from TT 148x to the latest version my users are reporting that opening any forestry machine GUI will cause a client crash like this:
http://pastebin.com/hC2NKb2L

Breaking and replacing these machines may solve the problem but item within them could be lost in this process (such as bees).

**Comment by mainsheep** [comment] 2013-05-06 09:16
My server has the same issue.

Did a couple of restarts, and right after restart they seemed fine. Probably since the chunk were loaded. But after a while it went back to crashing clients who right clicks them.

**Comment by LunNova** [comment] 2013-05-06 10:32
Possibly related to #446.Can anyone confirm if this started happening in build 1524?

**Comment by mainsheep** [comment] 2013-05-06 10:38
I installed 1537 yesteday evening, when I woke up today, players have had problems all night with this. Installed the TT1547 today, but still the same problem.

**Comment by LunNova** [comment] 2013-05-06 10:39
Check if any newly placed machines break with 1523.

**Comment by mainsheep** [comment] 2013-05-06 10:45
TT1523 fixed the problem, but players report that just after a restart, they worked before aswell.. I'm letting it run for another 10mins before I can give a 100% accurate report.

**Comment by mainsheep** [comment] 2013-05-06 10:51
Yes, problem is fixed with 1523.

**Comment by mainsheep** [comment] 2013-05-06 10:58
Update: The problem is fixed for some, but not for all.. From what I can figure, there is a connection to chunk loading/unloading and the players crashing.. The majority of the players report the problem is fixed however..

**Comment by wormzjl** [comment] 2013-05-06 11:36
Additional info: forestry multifarm works without problem.

**Comment by LunNova** [comment] 2013-05-06 15:23
Found the problem, the worldGenInProgress ThreadLocal was repeatedly being set to false, breaking my attempt at set-thread-counting optimisation.

**Comment by wormzjl** [comment] 2013-05-06 16:16
Problem fixed, good job nallar :D

**Comment by LunNova** [comment] 2013-05-06 16:31
If that did fix it there should be some console spam, please paste it.

Else, it just randomly started working again. I hate when that happens, you never know when the bug will happen again.

**Comment by wormzjl** [comment] 2013-05-06 16:35
Console spam as requested:

2013-05-06 12:33:18 [SEVERE] [ForgeModLoader] Exception loading chunk asynchronously.
java.lang.UnsupportedOperationException
    at aal.a(RegionFileCache.java)
    at aal.c(RegionFileCache.java:76)
    at CustomOreGen.Server.ServerState.isChunkSavedPopulated(ServerState.java:38)
    at CustomOreGen.Server.ServerState.onPopulateChunk(ServerState.java:269)
    at CustomOreGen.FMLInterface.generate(FMLInterface.java:95)
    at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:109)
    at im.populate(ThreadedChunkProvider.java:681)
    at im.tryPopulateChunks(ThreadedChunkProvider.java:572)
    at im.getChunkAtInternal(ThreadedChunkProvider.java:544)
    at im.getChunkAt(ThreadedChunkProvider.java:446)
    at me.nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:822)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by wormzjl** [comment] 2013-05-06 22:17
Seems that the problem is only partially solved, everything works except forestry bio generator.

**Comment by LunNova** [comment] 2013-05-07 17:30
@wormzjl 

Was the bio generator definitely placed after updating to the fixed version?

Also, that spam is unrelated, but fixed it in a6b6d6cb707c12ed4b9e469920d17363cf1e7119.

**Comment by wormzjl** [comment] 2013-05-07 20:39
It was placed before update, the new ones are fine.

**Comment by LunNova** [comment] 2013-05-07 20:44
Old machines may still be broken if loaded with TT while this issue was happening, nothing I can do about that. Closing as the issue appears to be fixed.

**Closed as completed by LunNova** 2013-05-07 20:44 UTC
Labels: bug, blocking
