### ISSUE TITLE
[Request] Guide to using /tick /profile /etc to find performance / blocking issues

### ISSUE THREAD

**Issue by geoffcorey** [MinimallyCorrect/TickThreading#501] opened 2013-05-16 17:20 UTC
Is there a guide or post somewhere that explains the proper use of these commands and the new options added in debugging server issues.     I am having a real issue with deadlocks and it looks like CC is the culprit but want to be sure.

**Comment by LunNova** [comment] 2013-05-16 17:23
Just make an issue with the deadlock detector report. There's no easy way to show what's causing deadlocks.

It tries to list only the threads involved in the deadlock at the bottom of the report, but in many cases this fails.

**Comment by geoffcorey** [comment] 2013-05-16 18:51
https://gist.github.com/geoffcorey/46bbd0cd36ac5e811511

**Comment by LunNova** [comment] 2013-05-16 19:47
Bad news, it is the computercraft deadlock that you suspected. This isn't something I can fix easily, it's fixed in newer computercraft versions. Not sure if it's fixed in any 1.4.7 versions though.

**Comment by geoffcorey** [comment] 2013-05-17 15:14
So interestingly enough I nuked a couple turtle startup scripts that I found were:

while true do
turtle.attack()
end

Note: No sleep line.

Still had the deadlock.   So I changed ChickenChunks.cfg setting to

#The number of ticks to wait between attempting to unload orphaned chunks
cleanuptime=12000

Which is an order of magnitude greater then the default and no more deadlock.    Go figure.

**Comment by LunNova** [comment] 2013-05-17 15:20
This is caused by wireless peripherals. There is a very low chance of it
happening, and even small changes can cause it to stop happening. TT
disables ChickenChunks' GC completely as it has a habit of trying to unload
stuff that it shouldn't.

If you're trying to find what causes lag spikes you can set the deadlock
time to 1 and it will make a report every time there's a spike, which will
hopefully show what caused it.

**Comment by geoffcorey** [comment] 2013-05-17 21:15
yeah we had a deadlock when I did a restart.   I will try the deadlock time approach next restart.

**Comment by LunNova** [comment] 2013-05-17 21:19
Oh, I added that as an irrelevant afterthought, it won't help with your problem. Sorry :( Kinda' surprised that the deadlock recovery didn't work though.

**Comment by geoffcorey** [comment] 2013-05-19 16:39
So I basically disabled wireless modems.  Set the range to 0.   Restarted with 1643 a few times while I setting various parameters and had a deadlock on mob spawning.   Changed     B:enableFastMobSpawning=true and also     B:shouldLoadSpawn=true and restarted.   So far no issues.

**Comment by geoffcorey** [comment] 2013-05-19 18:18
Odd side effect of using enableFastMobSpawning=true is an old school squid grinder no longer spawns squid.

**Comment by LunNova** [comment] 2013-05-19 18:51
Squid are only spawned in ocean or river biomes.

**Closed as completed** 2013-05-29 01:56 UTC
Labels: question
