### ISSUE TITLE
TT 1484 Uncaught Exception Handler in thread "Deadlock Detector"

### ISSUE THREAD

**Issue by Hoiafar** [MinimallyCorrect/TickThreading#421] opened 2013-05-01 15:13 UTC
Server refuses to close when started, the error itself won't show up until you try to log on. Which you can only do through Direct Connect because the server doesn't show up on the server browser.

Error message is very small so I'll just post it here.

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Deadlock Detecter"

**Comment by LunNova** [comment] 2013-05-01 17:08
You ran out of memory. Probably not a TT issue, increase the memory you're allocating to the server. If it only happens after running the server for a while it might be a memory leak.

**Comment by Hoiafar** [comment] 2013-05-01 17:10
It's given 4GB of memory. And it didn't happen until applying this patch of TT, the most it ever required before was 2.

**Comment by LunNova** [comment] 2013-05-01 17:41
Something definitely went wrong then, what mods are you using?

**Comment by Hoiafar** [comment] 2013-05-01 17:48
FTB Ultimate Pack. The only configuration we have done is change Greg Tech recipes.

**Comment by LunNova** [comment] 2013-05-01 19:49
Not encountered that then. Does this happen immediately? Try setting the chunk cache size to 0 in TT's config, that does increase memory usage. Although I wouldn't expect it to be increased that much.

**Comment by cjm721** [comment] 2013-05-01 22:44
Have not had this issue at all, but with 40 people playing on my Ultimate server only using 3.7GB

**Comment by Hoiafar** [comment] 2013-05-04 14:13
I think we figured out the problem. It is my Exp farm that's being clogged up by mobs when the turtles stop randomly working.

**Comment by LunNova** [comment] 2013-06-15 23:20
Closing this then, as it's caused by another open issue.

**Closed as completed by LunNova** 2013-06-15 23:20 UTC
Labels: bug
