### ISSUE TITLE
Completely failed to save a chunk!

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#133] opened 2013-02-11 11:53 UTC
It seems to be a problem with chickenchunks?,but not sure. i temporary removed it from the server. and it seems to work now.
I also have a option modified for that mod. only to work when the player is online
See log here:
http://pastebin.com/5buSTNyS

Also some strange things i have on server after installing TT:
- RP timers stop to rotate after server restart ?
- Also had a big problem with mob spawning. for some reason it had no cap. spawned like 10k entities (animals only ) .managed to cap it using aperf.

**Comment by coderjcronin** [comment] 2013-02-11 15:37
Same here; using latest build (918) and getting chunk save fails... appears to be areas where chunk loaders are being used.....
02-12 00:34:34 [SEVERE] [TickThreading] Failed to save a chunk, trying again.
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:839)
    at java.util.HashMap$ValueIterator.next(HashMap.java:868)
    at bq.a(SourceFile:24)
    at cd.a(SourceFile:114)
    at bq.a(SourceFile:25)
    at by.a(SourceFile:26)
    at cd.a(SourceFile:114)
    at bq.a(SourceFile:25)
    at cd.a(SourceFile:114)
    at bq.a(SourceFile:25)
    at cd.a(SourceFile:114)
    at ca.a(CompressedStreamTools.java:140)
    at aam.a(AnvilChunkLoader.java:198)
    at aam.c(AnvilChunkLoader.java:115)
    at aiw.b(SourceFile:29)
    at aiw.run(SourceFile:22)
    at java.lang.Thread.run(Thread.java:722)

**Comment by cronixia** [comment] 2013-02-11 18:12
Getting the same problem.

02-11 13:09:45 [SEVERE] [TickThreading] Failed to save a chunk, trying again.
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:839)
    at java.util.HashMap$ValueIterator.next(HashMap.java:868)
    at bq.a(SourceFile:24)
    at cd.a(SourceFile:114)
    at bq.a(SourceFile:25)
    at by.a(SourceFile:26)
    at cd.a(SourceFile:114)
    at bq.a(SourceFile:25)
    at cd.a(SourceFile:114)
    at bq.a(SourceFile:25)
    at cd.a(SourceFile:114)
    at ca.a(CompressedStreamTools.java:140)
    at aam.a(AnvilChunkLoader.java:198)
    at aam.c(AnvilChunkLoader.java:112)
    at aiw.b(SourceFile:29)
    at aiw.run(SourceFile:22)
    at java.lang.Thread.run(Unknown Source)

**Comment by LunNova** [comment] 2013-02-11 19:44
The comodification issues should be fixed in latest, not sure about the AIOOBE.

**Comment by LunNova** [comment] 2013-02-11 23:41
Can't reproduce the timer or mob spawning issues on latest.

**Comment by HaoSs07** [comment] 2013-02-12 11:13
ok. i will try the latest build today and come with feedback

the spawn problem is fixed. we talked on the FTB forum. i changed to fast spawning and its gone. don't know what happen really. to tell you how to reproduce it.spawned like 10k animals. capped with aperf. changed TT to fast spawn. removed cap from aperf . and that was it.

**Comment by HaoSs07** [comment] 2013-02-12 15:00
oh i remembered a thing about the spawn animals bug. it was only present when i had 20+ players.

**Closed as completed** 2013-02-14 23:37 UTC
Labels: bug
