### ISSUE TITLE
[build 205 | TPPI 1.0.3 modpack] Server cannot generate new terrain

### ISSUE THREAD

**Issue by stevestech** [MinimallyCorrect/TickThreading#1129] opened 2014-05-19 04:37 UTC
While exploring I noticed the following chunks failed to be loaded by my client. Logging in and out again, and even restarting the server failed to cause these chunks to load correctly. Was accompanied by this message:

```
2014-05-19 16:26:58 [SEVERE] [ForgeModLoader] Exception loading chunk asynchronously.
java.lang.UnsupportedOperationException
    at nallar.tickthreading.util.CounterThreadLocalAssumeZero.set(CounterThreadLocalAssumeZero.java:38)
    at nallar.tickthreading.util.CounterThreadLocalAssumeZero.increment(CounterThreadLocalAssumeZero.java:44)
    at net.minecraft.world.gen.ChunkProviderServer.populate(ThreadedChunkProvider.java:651)
    at net.minecraft.world.gen.ChunkProviderServer.tryPopulateChunks(ThreadedChunkProvider.java:687)
    at net.minecraft.world.gen.ChunkProviderServer.getChunkAtInternal(ThreadedChunkProvider.java:644)
    at net.minecraft.world.gen.ChunkProviderServer.getChunkAt(ThreadedChunkProvider.java:518)
    at nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:948)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
```

![2014-05-19_16 33 28](https://cloud.githubusercontent.com/assets/5620539/3010006/bd980c70-df0e-11e3-95a0-4751a286b2fd.png)

[ForgeModLoader-server-0.log](https://www.dropbox.com/s/yunlj7g0y9vn9q1/ForgeModLoader-server-0.log)
[patcher.1.log](https://www.dropbox.com/s/0h74pc49wn9g6ub/patcher.1.log)
[tickthreading.1.log](https://www.dropbox.com/s/qk9xijl7pgi64x8/tickthreading.1.log)

**Comment by stevestech** [comment] 2014-05-19 04:50
I later found that the server was unable to generate any new terrain, after deleting the region folder and restarting I was unable to connect to the server. Internal server error displayed on the client, and the console showed the same exception as above.

**Comment by LunNova** [comment] 2014-05-19 08:45
Duplicate of #1128, fixed.

**Closed as completed by LunNova** 2014-05-19 08:45 UTC
Labels: duplicate
