### ISSUE TITLE
lag deadlock

### ISSUE THREAD

**Issue by clienthax** [MinimallyCorrect/TickThreading#238] opened 2013-03-25 17:41 UTC
```
http://pastebin.com/rsky1rp1
```

**Comment by clienthax** [comment] 2013-03-25 17:44
https://mega.co.nz/#!aBUVVD6A!NmyShRaRarnQS03BFFF4mVCsaQk45iSu_nB5S0BAfgc

**Comment by LunNova** [comment] 2013-03-25 18:09
Duplicate of #235.

**Closed as completed by LunNova** 2013-03-25 18:09 UTC
Labels: duplicate
