### ISSUE TITLE
Exception in main tick loop

### ISSUE THREAD

**Issue by Zilacon** [MinimallyCorrect/TickThreading#1198] opened 2014-05-28 08:19 UTC
05-27 22:57:14 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
    at thermalexpansion.part.conduit.fluid.GridFluid.doGridUpdate(GridFluid.java:63)
    at thermalexpansion.part.conduit.GridTickHandler.tickEnd(GridTickHandler.java:76)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
    at nallar.tickthreading.util.WrappedScheduledTickHandler.tickEnd(WrappedScheduledTickHandler.java:27)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:80)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick_cpw_mods_fml_common_FMLCommonHandler_onPreServerTick_p0(FMLCommonHandler.java:274)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:330)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:183)
    at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)

Holy crap my servers on a error spree today...
Eventually it started doing this:
05-27 22:57:14 [SEVERE] [TickThreading] Exception in main tick loop
Stack trace unavailable for java.lang.NullPointerException-java.lang.NullPointerException. Add -XX:-OmitStackTraceInFastThrow to your java parameters to see all stack traces.

**Comment by Zilacon** [comment] 2014-05-28 21:52
This error is unbearable... Its just flooding my console to no end...

Just by having a Fluiduct loaded with liquids at all in it makes it go permanently insane, i broke the pipes and it continued to error forever...

**Comment by devryb** [comment] 2014-05-31 20:57
Duplicate of https://github.com/nallar/TickThreading/issues/1194

**Closed as completed** 2016-01-09 22:43 UTC
