### ISSUE TITLE
[TT 1859, MCPC L67] [SEVERE] java.lang.Exception

### ISSUE THREAD

**Issue by mainsheep** [MinimallyCorrect/TickThreading#701] opened 2013-06-11 09:30 UTC
These is spammed into the console from time to time.

04:28:46 [SEVERE] java.lang.Exception
04:28:46 [SEVERE]       at factorization.common.TileEntityBarrel.a(TileEntityBarrel.java:196)
04:28:46 [SEVERE]       at buildcraft.core.inventory.TransactorSimple.addToSlot(TransactorSimple.java:80)
04:28:46 [SEVERE]       at buildcraft.core.inventory.TransactorSimple.inject(TransactorSimple.java)
04:28:46 [SEVERE]       at buildcraft.core.inventory.Transactor.add(Transactor.java:16)
04:28:46 [SEVERE]       at buildcraft.transport.PipeTransportItems.handleTileReached(PipeTransportItems.java:334)
04:28:46 [SEVERE]       at buildcraft.transport.PipeTransportItems.moveSolids(PipeTransportItems.java:317)
04:28:46 [SEVERE]       at buildcraft.transport.PipeTransportItems.updateEntity(PipeTransportItems.java:225)
04:28:46 [SEVERE]       at buildcraft.transport.Pipe.updateEntity(Pipe.java:166)
04:28:46 [SEVERE]       at buildcraft.transport.TileGenericPipe.g(TileGenericPipe.java:189)
04:28:46 [SEVERE]       at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:93)
04:28:46 [SEVERE]       at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
04:28:46 [SEVERE]       at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
04:28:46 [SEVERE]       at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
04:28:46 [SEVERE]       at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
04:28:47 [SEVERE] java.lang.Exception
04:28:47 [SEVERE]       at factorization.common.TileEntityBarrel.a(TileEntityBarrel.java:196)
04:28:47 [SEVERE]       at buildcraft.core.inventory.TransactorSimple.addToSlot(TransactorSimple.java:80)
04:28:47 [SEVERE]       at buildcraft.core.inventory.TransactorSimple.inject(TransactorSimple.java)
04:28:47 [SEVERE]       at buildcraft.core.inventory.Transactor.add(Transactor.java:16)
04:28:47 [SEVERE]       at buildcraft.transport.PipeTransportItems.handleTileReached(PipeTransportItems.java:334)
04:28:47 [SEVERE]       at buildcraft.transport.PipeTransportItems.moveSolids(PipeTransportItems.java:317)
04:28:47 [SEVERE]       at buildcraft.transport.PipeTransportItems.updateEntity(PipeTransportItems.java:225)
04:28:47 [SEVERE]       at buildcraft.transport.Pipe.updateEntity(Pipe.java:166)
04:28:47 [SEVERE]       at buildcraft.transport.TileGenericPipe.g(TileGenericPipe.java:189)
04:28:47 [SEVERE]       at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:93)
04:28:47 [SEVERE]       at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:35)
04:28:47 [SEVERE]       at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:101)
04:28:47 [SEVERE]       at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:43)
04:28:47 [SEVERE]       at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by LunNova** [comment] 2013-06-15 19:18
Caused by broken TransactorSimple change, now fixed.

**Closed as completed by LunNova** 2013-06-15 19:18 UTC
Labels: bug
