### ISSUE TITLE
[TT #1320] [1.4.7 mcpc+ L15]  [WARNING] [ClearLag] Task #14 for ClearLag v2.1.1 generated an exception

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#317] opened 2013-04-16 17:25 UTC
Dam got another one of these errors :)

2013-04-16 15:58:44 [WARNING] [ClearLag] Task #14 for ClearLag v2.1.1 generated an exception
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:819)
    at java.util.ArrayList$Itr.next(ArrayList.java:791)
    at org.bukkit.craftbukkit.v1_4_R1.CraftWorld.getEntities(CraftWorld.java:624)
    at me.minebuilders.clearlag.managers.EntitiyManager.removeEntityLimit(Unknown Source)
    at me.minebuilders.clearlag.events.CheckLagEvent.run(Unknown Source)
    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:344)
    at net.minecraft.server.MinecraftServer.spigotTLETick(MinecraftServer.java)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:312)
    at ho.r(DedicatedServer.java:309)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:252)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:170)
    at fy.run(ThreadMinecraftServer.java:16)

**Comment by LunNova** [comment] 2013-04-16 17:27
No need to make a new isue, just reopen the old one. Closing as duplicate of #311.

**Closed as completed by LunNova** 2013-04-16 17:27 UTC
Labels: duplicate

**Comment by alicheek** [comment] 2013-04-16 17:28
@nallar 

Oh apologies though that one was closed ! :)
