### ISSUE TITLE
[SEVERE] [TickThreading-1.6.4.206] [MCPC] [1.6.4] Exception ticking TileEntity c thermalexpansion.block.machine.TileFurnace

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#1142] opened 2014-05-19 17:22 UTC
[SEVERE] [TickThreading] Exception ticking TileEntity c thermalexpansion.block.machine.TileFurnace @1673872350 in Overworld/0 at x, y, z: -5510, 64, 4851
java.lang.NullPointerException
        at thermalexpansion.block.machine.TileFurnace.processStart(TileFurnace.java:81)
        at thermalexpansion.block.machine.TileMachineEnergized.func_70316_g(TileMachineEnergized.java:134)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:173)
        at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:36)
        at nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.run(TileEntityTickRegion.java:126)
        at nallar.tickthreading.minecraft.ThreadManager$DelayableRunnable.run(ThreadManager.java:188)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)

**Comment by LunNova** [comment] 2014-05-19 17:41
Duplicate of #1112.

**Closed as completed by LunNova** 2014-05-19 17:41 UTC
Labels: duplicate
