### ISSUE TITLE
Every Build After #1503- Players cannot place blocks nor pick up items.

### ISSUE THREAD

**Issue by aquagene** [MinimallyCorrect/TickThreading#441] opened 2013-05-03 20:28 UTC
There's no errors, but with every build after #1503, players are almost completely unable to place blocks anywhere, nor pick up items on the floor.

**Comment by Nohau** [comment] 2013-05-03 20:32
Holy crap ultimate Grief Protection! 

Can a /op Pickup or place blocks

**Comment by aquagene** [comment] 2013-05-03 20:35
Nope, can't do either of those things myself as OP either.

**Comment by LunNova** [comment] 2013-05-03 21:04
Duplicate of #434.

**Closed as completed by LunNova** 2013-05-03 21:04 UTC
Labels: duplicate
