### ISSUE TITLE
Chunk Errors with [TT1716] 

### ISSUE THREAD

**Issue by Bucky420** [MinimallyCorrect/TickThreading#582] opened 2013-05-28 18:21 UTC
2013-05-28 20:19:35 [INFO] codydbgt: Complete!
2013-05-28 20:19:41 [INFO] codydbgt issued server command: /mv info
2013-05-28 20:19:44 [INFO] codydbgt issued server command: /mvtp spawn
2013-05-28 20:19:44 [INFO] Sending serverside check to: codydbgt
2013-05-28 20:19:47 [INFO] codydbgt issued server command: /mv list
2013-05-28 20:20:07 [INFO] There are 2 out of maximum 25 players online.
2013-05-28 20:20:07 [INFO] Mod: dr_blackenstien
2013-05-28 20:20:07 [INFO] Owner: [OWNER]codydbgt
2013-05-28 20:20:08 [INFO] [MineBackup]  \* saving worlds\DIM3
2013-05-28 20:20:11 [INFO] codydbgt issued server command: /mv tp spawn
2013-05-28 20:20:11 [INFO] Sending serverside check to: codydbgt
2013-05-28 20:20:14 [SEVERE] [ForgeModLoader] Exception posting event: net.minecraftforge.event.world.ChunkDataEvent$Load@6864485a
2013-05-28 20:20:14 [SEVERE] java.lang.NullPointerException
2013-05-28 20:20:14 [SEVERE]    at thaumcraft.common.AuraManager.generateNodeNeighbours(AuraManager.java:111)
2013-05-28 20:20:14 [SEVERE]    at thaumcraft.common.EventHandler.chunkLoad(EventHandler.java:213)
2013-05-28 20:20:14 [SEVERE]    at net.minecraftforge.event.ASMEventHandler_89_EventHandler_chunkLoad_Load.invoke(.dynamic)
2013-05-28 20:20:14 [SEVERE]    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
2013-05-28 20:20:14 [SEVERE]    at net.minecraftforge.event.EventBus.post(EventBus.java:104)
2013-05-28 20:20:14 [SEVERE]    at aam.a(ThreadedChunkLoader.java:188)
2013-05-28 20:20:14 [SEVERE]    at aam.a(ThreadedChunkLoader.java:159)
2013-05-28 20:20:14 [SEVERE]    at im.f(ThreadedChunkProvider.java:707)
2013-05-28 20:20:14 [SEVERE]    at im.getChunkAtInternal(ThreadedChunkProvider.java:528)
2013-05-28 20:20:14 [SEVERE]    at im.getChunkAt(ThreadedChunkProvider.java:502)
2013-05-28 20:20:14 [SEVERE]    at me.nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:881)
2013-05-28 20:20:14 [SEVERE]    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
2013-05-28 20:20:14 [SEVERE]    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
2013-05-28 20:20:14 [SEVERE]    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-28 20:20:14 [SEVERE] [ForgeModLoader] Exception posting event: net.minecraftforge.event.world.ChunkDataEvent$Load@2012258b
2013-05-28 20:20:14 [SEVERE] java.lang.NullPointerException
2013-05-28 20:20:14 [SEVERE]    at thaumcraft.common.AuraManager.generateNodeNeighbours(AuraManager.java:111)
2013-05-28 20:20:14 [SEVERE]    at thaumcraft.common.EventHandler.chunkLoad(EventHandler.java:213)
2013-05-28 20:20:14 [SEVERE]    at net.minecraftforge.event.ASMEventHandler_89_EventHandler_chunkLoad_Load.invoke(.dynamic)
2013-05-28 20:20:14 [SEVERE]    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
2013-05-28 20:20:14 [SEVERE]    at net.minecraftforge.event.EventBus.post(EventBus.java:104)
2013-05-28 20:20:14 [SEVERE]    at aam.a(ThreadedChunkLoader.java:188)
2013-05-28 20:20:14 [SEVERE]    at aam.a(ThreadedChunkLoader.java:159)
2013-05-28 20:20:14 [SEVERE]    at im.f(ThreadedChunkProvider.java:707)
2013-05-28 20:20:14 [SEVERE]    at im.getChunkAtInternal(ThreadedChunkProvider.java:528)
2013-05-28 20:20:14 [SEVERE]    at im.getChunkAt(ThreadedChunkProvider.java:502)
2013-05-28 20:20:14 [SEVERE]    at me.nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:881)
2013-05-28 20:20:14 [SEVERE]    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
2013-05-28 20:20:14 [SEVERE]    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
2013-05-28 20:20:14 [SEVERE]    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-28 20:20:18 [SEVERE] [ForgeModLoader] Exception posting event: net.minecraftforge.event.world.ChunkDataEvent$Load@c3f8610
2013-05-28 20:20:18 [SEVERE] java.lang.NullPointerException
2013-05-28 20:20:18 [SEVERE]    at thaumcraft.common.AuraManager.generateNodeNeighbours(AuraManager.java:111)
2013-05-28 20:20:18 [SEVERE]    at thaumcraft.common.EventHandler.chunkLoad(EventHandler.java:213)
2013-05-28 20:20:18 [SEVERE]    at net.minecraftforge.event.ASMEventHandler_89_EventHandler_chunkLoad_Load.invoke(.dynamic)
2013-05-28 20:20:18 [SEVERE]    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
2013-05-28 20:20:18 [SEVERE]    at net.minecraftforge.event.EventBus.post(EventBus.java:104)
2013-05-28 20:20:18 [SEVERE]    at aam.a(ThreadedChunkLoader.java:188)
2013-05-28 20:20:18 [SEVERE]    at aam.a(ThreadedChunkLoader.java:159)
2013-05-28 20:20:18 [SEVERE]    at im.f(ThreadedChunkProvider.java:707)
2013-05-28 20:20:18 [SEVERE]    at im.getChunkAtInternal(ThreadedChunkProvider.java:528)
2013-05-28 20:20:18 [SEVERE]    at im.getChunkAt(ThreadedChunkProvider.java:502)
2013-05-28 20:20:18 [SEVERE]    at me.nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:881)
2013-05-28 20:20:18 [SEVERE]    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
2013-05-28 20:20:18 [SEVERE]    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
2013-05-28 20:20:18 [SEVERE]    at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
2013-05-28 20:20:26 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.NullPointerException
        at java.util.LinkedList.unlink(Unknown Source)
        at java.util.LinkedList.remove(Unknown Source)
        at thaumcraft.common.AuraWorldTicker.tickEnd(AuraWorldTicker.java:63)
        at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:22)
        at me.nallar.tickthreading.util.WrappedScheduledTickHandler.tickEnd(WrappedScheduledTickHandler.java:28)
        at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:77)
        at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick_cpw_mods_fml_common_FMLCommonHandler_onPostWorldTick_p0(FMLCommonHandler.java:283)
        at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java)
        at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:509)
        at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:629)
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:44)

**Comment by LunNova** [comment] 2013-05-28 18:22
Duplicate of #579, you still haven't replied to my question there.

**Closed as completed by LunNova** 2013-05-28 18:22 UTC
Labels: duplicate
