### ISSUE TITLE
#1489 Mytown not recognizing players on login.

### ISSUE THREAD

**Issue by aquagene** [MinimallyCorrect/TickThreading#429] opened 2013-05-02 18:23 UTC
Mytown has constant problems in this build realizing a player is online, and giving them rights to the town they are a part of (They can't build or edit town permissions) I've turned off tickthreading and confirmed the problem is much more frequent with tickthreading.

**Comment by HaoSs07** [comment] 2013-05-02 18:41
this was also recognized to be a bug by mytown dev. Sometime losing connection to mysql

**Comment by aquagene** [comment] 2013-05-03 15:51
Yep, in #1503 as well players are not detected at all. It used to occur sometimes, and reloading mytown and PEX would fix it, but with the newer versions of tickthreading, rebooting or reloading does nothing, and towns just don't work at all. If I turn off tickthreading it works fine.

**Comment by LunNova** [comment] 2013-05-03 16:25
Can you find exactly which build this breaks in?

**Comment by aquagene** [comment] 2013-05-03 17:13
Tried a few different build, it breaks in #1488 as well. I just converted my server from using the built-in sqllite database of Mytown to a mysql server running separately and that works perfectly, if that helps any. Unfortunately it's not a bug I can provide much testing feedback in as I had to get towns working for my players asap, as no towns on a pvp allowed server had the potential to be devastating for my server. If others have this issue, going from sql lite to mysql fixes it.

**Comment by aquagene** [comment] 2013-05-03 18:58
Ok, I've found out what the problem is exactly, as it started happening with my mysql table as well. It's writing the data to the mysql table multiple times, so instead of pulling the rights data from an existing entry, it's making a new blank one and ignoring if a player is a mayor, etc. I'm not 100% sure if this is a tickthreading issue or a mytown issue, but it def happens way more often with tickthreading. Nonetheless I'll report it to the mytown thread as well, as it DOES happen without tickthreading.

**Comment by HaoSs07** [comment] 2013-05-03 19:20
well as i stated before :P "this was also recognized to be a bug by mytown dev. Sometime losing connection to mysql" 
i reported this around 2 months ago, i have it rarely , like 6 times in 4 months,and only to 2-3 players, you have mysql on localhost?

**Comment by aquagene** [comment] 2013-05-03 19:27
Yeah, it's running off localhost.

**Comment by HaoSs07** [comment] 2013-05-21 17:17
I have an update on this, seems mytown => mysql goes crazy when you use /ta reload.

and a fix for this, kill server then: connect to mysql using phpmyadmin, go to sql and run:

SELECT name, COUNT(*) c FROM residents GROUP BY name HAVING c > 1;

see what names are duplicated, search individual name in residents table and delete the one with bigger ID. ( you can also do this auto using this : 
DELETE n1 FROM residents n1, residents n2 WHERE n1.id > n2.id AND n1.name = n2.name

This will delete duplicate Name from residents and will keep the lowest id.
Is best to run this as soon as the problem is reported by players

If you want to test first use : 
create table test like residents; 
insert test select \* from residents

Then use this to see duplicate names : 

SELECT name, COUNT(*) c FROM test GROUP BY name HAVING c > 1;

Then run this 

DELETE n1 FROM test n1, test n2 WHERE n1.id > n2.id AND n1.name = n2.name

and then this again to see it worked

SELECT name, COUNT(*) c FROM test GROUP BY name HAVING c > 1;

then : 
drop table test

**Comment by LunNova** [comment] 2013-05-21 18:11
Make name a unique key in that table and it will prevent this from happening. Although MyTown may fail to cope with that change.

**Closed as completed** 2013-05-29 15:14 UTC
Labels: bug, MCPC+
