### ISSUE TITLE
Trees not gorwing with TT on

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#1147] opened 2014-05-19 21:43 UTC
Haven't got any error logs from it but for some reason with TT on when you use bone meal on a sapling it doesn't grow, nor does the trees seem to grow naturally .

**Comment by Katelyn-SN** [comment] 2014-05-19 21:56
Close - Duplicate of #1087

**Closed as completed** 2014-05-19 22:00 UTC
Labels: duplicate
