### ISSUE TITLE
[TT1927, MCPCL 67]  [SEVERE] [TickThreading] Failed to handle packet from unknown

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#749] opened 2013-06-17 12:08 UTC
[WARNING] [TickThreading] it@7413e66a sent a movement update before properly connecting. It will be ignored.
2013-06-17 04:02:19 [SEVERE] [TickThreading] Failed to handle packet from unknown
java.io.IOException: Received string length longer than maximum allowed (7424 > 16)
    at ef.a(Packet.java:240)
    at cy.a(Packet2ClientProtocol.java:33)
    at ef.a(Packet.java:175)
    at cg.i(TcpConnection.java:325)
    at cg.readNetworkPacket(TcpConnection.java:71)
    at ch.run(ReplaceTcpReaderThread.java:22)

**Comment by LunNova** [comment] 2013-06-20 16:53
Duplicate of #674.

**Closed as completed by LunNova** 2013-06-20 16:53 UTC
Labels: duplicate

**Comment by alicheek** [comment] 2013-06-20 16:54
my bad sorry
