### ISSUE TITLE
server sill does not save properly 

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#295] opened 2013-04-13 17:46 UTC
04-13 20:42:46 [WARNING] [TickThreading] Save queue overloaded in Overworld/0 consider decreasing saveInterval. Only saved 256 out of 3086 (WOOOT ?)

save interval is set to 6000 ticks  (( 5 minutes )) but only saves 256 on each run,the interval seems to be irrelevant... player still lose placed items, as chunks are reloaded but are not saved...

**Comment by LunNova** [comment] 2013-04-13 17:48
6000 is far too high. However, the reloading but not saved issue is something different - saveInterval is irrelevant for that issue. Probably best not to use TT until that's fixed :p

Closing as duplicate of #294

**Closed as completed by LunNova** 2013-04-13 17:48 UTC
