### ISSUE TITLE
tropicraft issue ?

### ISSUE THREAD

**Issue by Bucky420** [MinimallyCorrect/TickThreading#1163] opened 2014-05-25 17:04 UTC
05-25 13:02:54 [INFO] [Minecraft] SERIOUS REFLECTION FAIL IN DimensionChunkCache
05-25 13:02:54 [SEVERE] [Minecraft] java.lang.NullPointerException
05-25 13:02:54 [SEVERE] [Minecraft]     at CoroAI.DimensionChunkCache.<init>(DimensionChunkCache.java:83)
05-25 13:02:54 [SEVERE] [Minecraft]     at CoroAI.DimensionChunkCache.updateAllWorldCache(DimensionChunkCache.java:53)
05-25 13:02:54 [SEVERE] [Minecraft]     at CoroAI.PFQueue.tryPath(PFQueue.java:556)
05-25 13:02:54 [SEVERE] [Minecraft]     at CoroAI.PFQueue.tryPath(PFQueue.java:538)
05-25 13:02:54 [SEVERE] [Minecraft]     at CoroAI.PFQueue.getPath(PFQueue.java:527)
05-25 13:02:54 [SEVERE] [Minecraft]     at CoroAI.PFQueue.getPath(PFQueue.java:523)
05-25 13:02:54 [SEVERE] [Minecraft]     at CoroAI.componentAI.AIAgent.walkTo(AIAgent.java:829)
05-25 13:02:54 [SEVERE] [Minecraft]     at CoroAI.componentAI.AIAgent.walkTo(AIAgent.java:824)
05-25 13:02:54 [SEVERE] [Minecraft]     at CoroAI.componentAI.AIAgent.updateWanderPath(AIAgent.java:793)
05-25 13:02:54 [SEVERE] [Minecraft]     at CoroAI.componentAI.jobSystem.JobBase.onIdleTickAct(JobBase.java:193)
05-25 13:02:54 [SEVERE] [Minecraft]     at CoroAI.componentAI.jobSystem.JobBase.onIdleTick(JobBase.java:180)
05-25 13:02:54 [SEVERE] [Minecraft]     at CoroAI.componentAI.AIAgent.updateAI(AIAgent.java:599)
05-25 13:02:54 [SEVERE] [Minecraft]     at CoroAI.componentAI.AIAgent.updateAITasks(AIAgent.java:339)
05-25 13:02:54 [SEVERE] [Minecraft]     at tropicraft.entities.hostile.EntityLand.func_70619_bc(EntityLand.java:119)
05-25 13:02:54 [SEVERE] [Minecraft]     at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:196)
05-25 13:02:54 [SEVERE] [Minecraft]     at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java)
05-25 13:02:54 [SEVERE] [Minecraft]     at tropicraft.entities.hostile.EntityLand.func_70636_d(EntityLand.java:193)
05-25 13:02:54 [SEVERE] [Minecraft]     at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1973)
05-25 13:02:54 [SEVERE] [Minecraft]     at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:264)
05-25 13:02:54 [SEVERE] [Minecraft]     at net.minecraft.world.World.func_72866_a(World.java:387)
05-25 13:02:54 [SEVERE] [Minecraft]     at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:1006)
05-25 13:02:54 [SEVERE] [Minecraft]     at net.minecraft.world.World.func_72870_g(World.java:2891)
05-25 13:02:54 [SEVERE] [Minecraft]     at nallar.tickthreading.minecraft.tickregion.EntityTickRegion.doTick(EntityTickRegion.java:61)
05-25 13:02:54 [SEVERE] [Minecraft]     at nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:36)
05-25 13:02:54 [SEVERE] [Minecraft]     at nallar.tickthreading.minecraft.ThreadManager$DelayableRunnable.run(ThreadManager.java:188)
05-25 13:02:54 [SEVERE] [Minecraft]     at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
05-25 13:02:54 [SEVERE] [Minecraft]     at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
05-25 13:02:54 [INFO] [Minecraft] DimensionChunkCache crash, tell Corosus
05-25 13:03:35 [INFO] [Minecraft] DimensionChunkCache crash, tell Corosus
05-25 13:03:37 [INFO] [Minecraft] Connection reset
05-25 13:03:37 [INFO] [Minecraft] migges18 lost connection: disconnect.quitting
05-25 13:03:40 [INFO] [Minecraft] J1:0 K1:8
05-25 13:03:41 [INFO] [Minecraft] Nerezza Goblin was slain by ebayaz
05-25 13:03:44 [SEVERE] [ForgeModLoader] An Entity type tropicraft.entities.passive.land.VMonkey at Tropics/-127,-268.500000,67.000000,-
1144.500000 has thrown an exception trying to write state. It will not persist. Report this to the mod author
net.minecraft.util.ReportedException: Saving entity NBT
        at net.minecraft.entity.Entity.func_70109_d(Entity.java:1827)
        at net.minecraft.entity.Entity.func_70039_c(Entity.java:1748)
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(ThreadedChunkLoader.java:332)
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(ThreadedChunkLoader.java:203)
        at net.minecraft.world.gen.ChunkProviderServer.saveChunk(ThreadedChunkProvider.java:783)
        at net.minecraft.world.gen.ChunkProviderServer.finalizeUnload(ThreadedChunkProvider.java:254)
        at net.minecraft.world.gen.ChunkProviderServer.handleUnloadQueue(ThreadedChunkProvider.java:229)
        at net.minecraft.world.gen.ChunkProviderServer.handleUnloadQueue(ThreadedChunkProvider.java:214)
        at net.minecraft.world.gen.ChunkProviderServer.tick_net_minecraft_world_gen_ChunkProviderServer_tick_p0(ThreadedChunkProvider.java:185)
        at net.minecraft.world.gen.ChunkProviderServer.tick(ThreadedChunkProvider.java)
        at net.minecraft.world.WorldServer.func_72835_b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:411)
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java)
        at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:519)
        at nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:674)
        at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
        at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
Caused by: java.lang.NullPointerException
        at tropicraft.entities.hostile.EntityLand.func_70014_b(EntityLand.java:139)
        at net.minecraft.entity.Entity.func_70109_d(Entity.java:1810)
        ... 15 more

**Comment by Jasnatdic** [comment] 2014-05-26 03:23
TickThreading doesn't patch CoroAI, the dependency of Tropicraft, Zombie Awareness, Zombiecraft and i think also the weather mod. This isn't a bug, its simply a lack of support currently for a mod. Also, this issue is a duplicate of issue #1084

**Closed as completed** 2014-05-26 13:17 UTC
Labels: duplicate
