### ISSUE TITLE
Wierd networking issues (last 200 odd builds)

### ISSUE THREAD

**Issue by clienthax** [MinimallyCorrect/TickThreading#392] opened 2013-04-28 13:15 UTC
One thing ive noticed with tt is that if you are getting ALOT of logins, say in the range of 20 every few seconds, it will only allow the first 10-30 on and the rest will seem to lag out for a few mins then you will get a mass join of about 100 players

**Comment by alicheek** [comment] 2013-04-28 13:21
must admit ive never got this; my server only holds 60 people though but when ever ive restarted it when its full and they all come back on fine, I haven't noticed anything strange

**Comment by LunNova** [comment] 2013-04-28 15:30
I've also not run into this. Can you keep `htop` open while starting the server, do all CPU cores reach 100% usage? Might be completely overloading the server with so many people trying to connect.

Does enabling concurrent network ticks fix this?

**Comment by clienthax** [comment] 2013-04-28 21:53
@nallar still same issue with concurrent network ticks, enabling it actually seems to increase the effect, can't realy enable tt on my server atm due to it making all the ue wires act wierd

**Comment by LunNova** [comment] 2013-06-15 16:31
This should be fixed now. It might have been caused by the lag spike from loading persistent chunks on server start, which now should happen asynchronously. Additionally, some other non-async chunkloading issues which could cause lag spikes have been fixed.

**Closed as completed** 2013-06-15 16:31 UTC
Labels: bug, MCPC+
