### ISSUE TITLE
[TT 1826, MCPC+ L38] [SEVERE] [TickThreading] Failed to handle packet from canadiangirl1

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#652] opened 2013-06-03 16:17 UTC
[SEVERE] [TickThreading] Failed to handle packet from canadiangirl1
java.util.EmptyStackException
    at java.util.Stack.peek(Stack.java:102)
    at java.util.Stack.pop(Stack.java:84)
    at chb.mods.mffs.network.server.ForceFieldServerUpdatehandler.tickEnd(ForceFieldServerUpdatehandler.java:46)
    at me.nallar.tickthreading.util.WrappedScheduledTickHandler.tickEnd(WrappedScheduledTickHandler.java:28)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:77)
    at cpw.mods.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:390)
    at qx.j_(EntityPlayer.java:418)
    at iq.g(EntityPlayerMP.java:359)
    at iv.a(NetServerHandler.java:499)
    at eb.a(Packet10Flying.java:68)
    at cg.i(TcpConnection.java:348)
    at cg.readNetworkPacket(TcpConnection.java:71)
    at ch.run(ReplaceTcpReaderThread.java:22)

**Comment by CappyT** [comment] 2013-06-03 21:17
Think is duplicated of #651

**Comment by HaoSs07** [comment] 2013-06-04 17:51
no is not. here we have a canadiangirl , you have DrMale. girls win.so your report its a duplicate of this.

**Comment by LunNova** [comment] 2013-06-16 15:41
Duplicate of #651, which is also fixed.

**Closed as completed by LunNova** 2013-06-16 15:41 UTC
Labels: duplicate
