### ISSUE TITLE
Another Exception Ticking issue

### ISSUE THREAD

**Issue by ray73864** [MinimallyCorrect/TickThreading#210] opened 2013-03-15 04:09 UTC
I know there are a couple of these ones, but anyway.

I installed this mod today for the first time to give it a go, it appeared to work out, but then i used my mystcraft book to go to my nether fortress, all appeared to work fine, then i used the book i had there to go back to my base in the overworld and BAM the issues started.

I was stuck staring at nothing but void, there was no world around me at all, it was apparently having a great deal of difficulty loading the world.

I am running the Ultimate pack, which has a whole lot of extra mods on top of the standard ones that come with the Mindcrack and Direwolf packs.

This one error is basically the only 1 appearing in the logfile:

``` java
03-14 20:29:28 [SEVERE] [TickThreading] Exception ticking world Overworld/0
java.lang.NullPointerException
    at soaryn.xycraft.machines.block.XyCraftWorldExtension.defer(XyCraftWorldExtension.java:231)
    at soaryn.xycraft.machines.block.XyCraftChunkExtension.unload(XyCraftChunkExtension.java:137)
    at codechicken.xycraftcopy.core.world.WorldExtension.unloadChunk(WorldExtension.java:52)
    at codechicken.xycraftcopy.core.world.WorldExtensionManager$WorldExtensionEventHandler.onChunkUnLoad(WorldExtensionManager.java:70)
    at net.minecraftforge.event.ASMEventHandler_193_WorldExtensionEventHandler_onChunkUnLoad_Unload.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at im.finalizeUnload(ThreadedChunkProvider.java:194)
    at im.tick(ThreadedChunkProvider.java:165)
    at im.b(ThreadedChunkProvider.java:107)
    at in.b_net_minecraft_world_WorldServer_tick_p0(WorldServer.java:276)
    at in.b(WorldServer.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:442)
    at me.nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:543)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
```

**Comment by LunNova** [comment] 2013-03-17 01:45
Duplicate of #210.

**Comment by LunNova** [comment] 2013-03-17 01:46
Oops? I won't even edit that stupid reply out! Sorry.

Actually a duplicate of #209.

**Closed as completed by LunNova** 2013-03-17 01:45 UTC
Labels: bug, duplicate
