### ISSUE TITLE
[TT 1424] [MCPC+ L15]  [SEVERE] [TickThreading] Exception during tile entity tick mffs

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#377] opened 2013-04-24 14:11 UTC
Been getting this spam in my TT log with the latest build:

2013-04-24 06:59:49 [SEVERE] [TickThreading] Exception during tile entity tick
ticking: c chb.mods.mffs.common.tileentity.TileEntityProjector chb.mods.mffs.common.tileentity.TileEntityProjector@1fa52c1b x,y,z: 47, 55, 841 at x,y,z:47,55,841
Tick region: rX: 2, rZ: 52, hashCode: 3407874:
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:839)
    at java.util.HashMap$KeyIterator.next(HashMap.java:874)
    at chb.mods.mffs.common.options.ItemProjectorOptionFieldFusion.checkFieldFusioninfluence(ItemProjectorOptionFieldFusion.java:53)
    at chb.mods.mffs.common.tileentity.TileEntityProjector.Forcefielddefine(TileEntityProjector.java:659)
    at chb.mods.mffs.common.tileentity.TileEntityProjector.calculateField(TileEntityProjector.java:606)
    at chb.mods.mffs.common.tileentity.TileEntityProjector.destroyField(TileEntityProjector.java:798)
    at chb.mods.mffs.common.tileentity.TileEntityProjector.g(TileEntityProjector.java:559)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
2013-04-24 06:59:49 [SEVERE] [TickThreading] Exception during tile entity tick
ticking: c chb.mods.mffs.common.tileentity.TileEntityProjector chb.mods.mffs.common.tileentity.TileEntityProjector@27d3061d x,y,z: 67, 55, 820 at x,y,z:67,55,820
Tick region: rX: 4, rZ: 51, hashCode: 3342340:
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:839)
    at java.util.HashMap$KeyIterator.next(HashMap.java:874)
    at chb.mods.mffs.common.options.ItemProjectorOptionFieldFusion.checkFieldFusioninfluence(ItemProjectorOptionFieldFusion.java:53)
    at chb.mods.mffs.common.tileentity.TileEntityProjector.Forcefielddefine(TileEntityProjector.java:659)
    at chb.mods.mffs.common.tileentity.TileEntityProjector.calculateField(TileEntityProjector.java:606)
    at chb.mods.mffs.common.tileentity.TileEntityProjector.destroyField(TileEntityProjector.java:798)
    at chb.mods.mffs.common.tileentity.TileEntityProjector.g(TileEntityProjector.java:559)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
2013-04-24 07:25:55 [SEVERE] [TickThreading] Exception during tile entity tick
ticking: c chb.mods.mffs.common.tileentity.TileEntityProjector chb.mods.mffs.common.tileentity.TileEntityProjector@706d1e81 x,y,z: 47, 55, 820 at x,y,z:47,55,820
Tick region: rX: 2, rZ: 51, hashCode: 3342338:
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:839)
    at java.util.HashMap$KeyIterator.next(HashMap.java:874)
    at chb.mods.mffs.common.options.ItemProjectorOptionFieldFusion.checkFieldFusioninfluence(ItemProjectorOptionFieldFusion.java:53)
    at chb.mods.mffs.common.tileentity.TileEntityProjector.Forcefielddefine(TileEntityProjector.java:659)
    at chb.mods.mffs.common.tileentity.TileEntityProjector.calculateField(TileEntityProjector.java:606)
    at chb.mods.mffs.common.tileentity.TileEntityProjector.g(TileEntityProjector.java:546)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
2013-04-24 07:35:50 [SEVERE] [TickThreading] Exception during tile entity tick
ticking: c chb.mods.mffs.common.tileentity.TileEntityProjector chb.mods.mffs.common.tileentity.TileEntityProjector@27d3061d x,y,z: 67, 55, 820 at x,y,z:67,55,820
Tick region: rX: 4, rZ: 51, hashCode: 3342340:
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:839)
    at java.util.HashMap$KeyIterator.next(HashMap.java:874)
    at chb.mods.mffs.common.options.ItemProjectorOptionFieldFusion.checkFieldFusioninfluence(ItemProjectorOptionFieldFusion.java:53)
    at chb.mods.mffs.common.tileentity.TileEntityProjector.Forcefielddefine(TileEntityProjector.java:659)
    at chb.mods.mffs.common.tileentity.TileEntityProjector.calculateField(TileEntityProjector.java:606)
    at chb.mods.mffs.common.tileentity.TileEntityProjector.destroyField(TileEntityProjector.java:798)
    at chb.mods.mffs.common.tileentity.TileEntityProjector.g(TileEntityProjector.java:559)
    at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
    at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
    at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)
    at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
    at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)
2013-04-24 07:35:50 [SEVERE] [TickThreading] Exception during tile entity tick
ticking: c chb.mods.mffs.common.tileentity.TileEntityProjector chb.mods.mffs.common.tileentity.TileEntityProjector@706d1e81 x,y,z: 47, 55, 820 at x,y,z:47,55,820
Tick region: rX: 2, rZ: 51, hashCode: 3342338:

**Comment by aquagene** [comment] 2013-04-24 18:39
May be related, an issue with fieldfusion from awhile back https://github.com/nallar/TickThreading/issues/184

**Comment by LunNova** [comment] 2013-04-26 20:12
Closing as duplicate of #184, will get #184 fixed soon. Sorry about the delay, been busy :(

**Closed as completed by LunNova** 2013-04-26 20:12 UTC
Labels: duplicate

**Comment by alicheek** [comment] 2013-04-26 20:13
no worries man take your time :)
