### ISSUE TITLE
Please place all information on barrel issues here.

### ISSUE THREAD

**Issue by ghost** [MinimallyCorrect/TickThreading#1021] opened 2013-11-24 21:48 UTC
Nallar has stated he will attempt to fix the issue if we gather him some clear, concise information.

**Comment by mrfrase3** [comment] 2013-12-10 21:39
idk, they still seem to work on our server with TT installed, been like that for six months....

**Comment by LunNova** [comment] 2014-01-04 18:13
Since no-one actually gave steps to reproduce, and apparently it wasn't acutally an issue, closing this.

**Closed as completed** 2014-01-04 18:13 UTC
Labels: invalid/wontfix
