### ISSUE TITLE
IC2 broken with TT patch

### ISSUE THREAD

**Issue by Tencao** [MinimallyCorrect/TickThreading#887] opened 2013-07-12 05:14 UTC
Using IC2 build 385, and TT version 124
Power wont transfer between machines and cables. I've confirmed this works on single player using the exact same mods and configs, excluding TT, so I'm almost positive that this is a TT issue.

**Comment by LunNova** [comment] 2013-07-12 13:57
Issue with newer IC2 dev builds.

https://github.com/MinecraftPortCentral/MCPC-Plus-Legacy/issues/1368
https://github.com/nallar/TickThreading/issues/852

Closing as duplicate of #852.

**Closed as completed by LunNova** 2013-07-12 13:57 UTC
Labels: duplicate
