### ISSUE TITLE
Fluid Conduit NPE

### ISSUE THREAD

**Issue by Katelyn-SN** [MinimallyCorrect/TickThreading#1102] opened 2014-05-11 06:53 UTC
```
05-11 02:21:12 [SEVERE] [TickThreading] Exception in main tick loop
java.lang.NullPointerException
    at thermalexpansion.part.conduit.fluid.GridFluid.doGridUpdate(GridFluid.java:63)
    at thermalexpansion.part.conduit.GridTickHandler.tickEnd(GridTickHandler.java:75)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
    at nallar.tickthreading.util.WrappedScheduledTickHandler.tickEnd(WrappedScheduledTickHandler.java:27)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:80)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick_cpw_mods_fml_common_FMLCommonHandler_onPreServerTick_p0(FMLCommonHandler.java:274)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:331)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:186)
    at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
```

**Comment by LunNova** [comment] 2014-05-11 10:51
~~Can you post the patcher log? One of the recent changes was intended to fix this, not sure if the patching failed or the patch just doesn't fix it.~~

edit: Nevermind, thinking of something else.

**Comment by LunNova** [comment] 2014-05-11 11:00
Also note, this is similar to but not a duplicate of #1096.

**Closed as completed** 2014-05-13 20:40 UTC
Labels: bug
