### ISSUE TITLE
#1493 Redpower bug/crash

### ISSUE THREAD

**Issue by HaoSs07** [MinimallyCorrect/TickThreading#430] opened 2013-05-02 18:44 UTC
2013-05-02 21:41:38 [SEVERE] [TickThreading] Exception ticking TileEntity c factorization.common.TileEntityWrathLamp factorization.common.TileEntityWrathLamp@21d1ff77 x,y,z: 1978, 53, -177 at x,y,z:1978,53,-177

 World: Overworld/0

java.lang.VerifyError: (class: com/eloraam/redpower/core/TubeFlow, method: &lt;init&gt; signature: ()V) Unable to pop operand off an empty stack

  at com.eloraam.redpower.machine.TileTube.&lt;init&gt;(TileTube.java:74)

  at sun.reflect.GeneratedConstructorAccessor91.newInstance(Unknown Source)

  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)

  at java.lang.reflect.Constructor.newInstance(Unknown Source)

  at java.lang.Class.newInstance0(Unknown Source)

  at java.lang.Class.newInstance(Unknown Source)

  at any.c(TileEntity.java:139)

  at aam.a(ThreadedChunkLoader.java:412)

  at aam.a(ThreadedChunkLoader.java:133)

  at aam.a(ThreadedChunkLoader.java:109)

  at im.f(ThreadedChunkProvider.java:572)

  at im.getChunkAtInternal(ThreadedChunkProvider.java:453)

  at im.d(ThreadedChunkProvider.java:359)

  at yc.e(World.java:524)

  at yc.b(World.java:590)

  at yc.e(World.java:700)

  at factorization.common.TileEntityWrathLamp$InitialBuild.update(TileEntityWrathLamp.java:293)

  at factorization.common.TileEntityWrathLamp.g(TileEntityWrathLamp.java:135)

  at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)

  at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)

  at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:90)

  at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)

  at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:157)

**Comment by LunNova** [comment] 2013-05-02 18:44
Duplicate of #428.

**Closed as completed by LunNova** 2013-05-02 18:44 UTC
Labels: duplicate

**Comment by HaoSs07** [comment] 2013-05-02 18:47
ok, I skipped checking reports made for mcpc
