### ISSUE TITLE
Minions Exception ticking world - Occurs in all worlds

### ISSUE THREAD

**Issue by Katelyn-SN** [MinimallyCorrect/TickThreading#1124] opened 2014-05-17 21:25 UTC
```
05-17 00:28:55 [SEVERE] [TickThreading] Exception ticking world Creative/4
java.lang.NullPointerException
    at atomicstryker.minions.common.jobmanager.Minion_Job_DigMineStairwell.onJobUpdateTick(Minion_Job_DigMineStairwell.java:56)
    at atomicstryker.minions.common.MinionsCore.onTick(MinionsCore.java:195)
    at atomicstryker.minions.common.MinionsCore$ServerTickHandler.tickEnd(MinionsCore.java:705)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
    at nallar.tickthreading.util.WrappedScheduledTickHandler.tickEnd(WrappedScheduledTickHandler.java:27)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:80)
    at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick_cpw_mods_fml_common_FMLCommonHandler_onPreServerTick_p0(FMLCommonHandler.java:282)
    at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java)
    at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:524)
    at nallar.patched.server.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:675)
    at nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:40)
    at nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
```

Also a memory leak is occuring not sure if it is caused by TT

**Comment by LunNova** [comment] 2014-05-17 22:21
Duplicate of #1097.

**Closed as completed by LunNova** 2014-05-17 22:21 UTC
Labels: duplicate
