### ISSUE TITLE
TT patching fail and dont even start

### ISSUE THREAD

**Issue by Vycraftujto** [MinimallyCorrect/TickThreading#1079] opened 2014-05-07 19:31 UTC
Load of patching errors and server stops and yes we have a shitload of mods

https://gist.github.com/Vycraftujto/1ae68d264258e4f7c784

**Comment by LunNova** [comment] 2014-05-07 19:42
What is the command you're using to start the server?

**Comment by Vycraftujto** [comment] 2014-05-07 19:49
run.bat:
java -Xms256M -Xmx5G -XX:MaxPermSize=256M -XX:+UseParNewGC -jar TickThreading.jar --log-limit 262144000 --serverJar=mcpc965.jar
pause

**Comment by Vycraftujto** [comment] 2014-05-07 19:50
It is a clone of main server 

launching it from windows on mine PC and yes it work whit out TT ..

PS: thanks for all good work acros all patches

**Comment by Katelyn-SN** [comment] 2014-05-07 20:59
TickThreading does not use the --serverJar argument anymore check the folder that your TickThreading.jar is in for ttlaunch.properties and add your mcpc jar name into it.

**Comment by Vycraftujto** [comment] 2014-05-07 21:17
NEW run.bat: java -Xms256M -Xmx5G -XX:MaxPermSize=256M -jar TickThreading.jar
pause
ok done that (thx btw that will be good for future) ..

But same result errors PATCHING FAILED and then server stop
Im tried this in hosting server as well same result so not machine isue.

**Comment by Katelyn-SN** [comment] 2014-05-07 21:25
What pack are you using

**Comment by Vycraftujto** [comment] 2014-05-07 21:28
Ours yea im know it dont tell you much:) we are normali 1 year ahead whit mods then tekkit. yes we have loads of mods but never hade any problems.... used tt in 1.4 and 1.5 whit no problems.

Closest im can tell is FTB to what we use but no magic mods

NOW IM DELETING ONE MOD AFTER NOTHER TO FIND IF IT IS SINGLE MOD RELATED
(Probabli shud done that as first thing sry.)

**Comment by LunNova** [comment] 2014-05-07 22:24
If possible could you upload a zip of the your server jar, TT jar, mods folder and configs folder?

This is probably a horrible classloader issue and it'd be much easier to debug if I can test it locally.

**Comment by LunNova** [comment] 2014-05-07 22:27
I'll have a new build up soon with some more debugging for this. Try that build, then post the log here.

If I can't figure out a solution from that extra information, then you'll need to send what I asked for in the previous comment.

**Comment by Vycraftujto** [comment] 2014-05-07 22:30
OK found a problem MicdoodleCore-1.6.4-2.0.11.978.jar CORE of GALACTICRAFT is what causing the isue

**Comment by LunNova** [comment] 2014-05-07 22:35
Try the latest build with that mod installed, and link the new full error log - even if it now works correctly with that mod, still post a full log.

**Comment by Vycraftujto** [comment] 2014-05-07 22:40
OK 151 fixed the isue loaded up whit all mods

But still got load of 

TTPatcher] Failed to patch (many mods)

im guess not implemented yet

**Comment by LunNova** [comment] 2014-05-07 22:43
> Try the latest build with that mod installed, _**and link the new full error log - even if it now works correctly with that mod, still post a full log.**_

**Comment by Vycraftujto** [comment] 2014-05-07 22:47
FML LOG
https://gist.github.com/Vycraftujto/c5954eef90d5d71c9332
server log 
https://gist.github.com/Vycraftujto/f3b18933b1336bfa2137

tested whit all mods working whit errors but working 

im just send you our MODS + config + mcpc + TT in mail for better securyty loads of people from our country wanna steal our server configuration

**Comment by LunNova** [comment] 2014-05-07 22:56
Okay, most of those will be fixed in latest. Still some GT patch issues, but your main issue is fixed. It was caused by MicdoodleTransformer being stupid and creating a new LaunchClassLoader instance just to check whether it's running under obfuscated minecraft.

**Closed as completed by LunNova** 2014-05-07 22:56 UTC
Labels: bug
